### ISSUE TITLE
Smart merge not working

### ISSUE THREAD

**Issue by mohtamohit** [Unity-Technologies/Tanto#40]
The issue has less to do with this repository. But, would just like to know whether this tool is up here? Actually, for a better collaboration among my teammates I need assistance to merge two unity scenes. The UnityYamlMerge tool opens and suffers crash in 5 seconds. As a result, I have been unable to merge two scenes. I saw a few posts on the unity forum regarding the same but found no fix and as a result I'm stuck now. Hope this collaboration tool solves that issue. And, meanwhile, someone here who could help me out?

![screenshot 2](https://cloud.githubusercontent.com/assets/16120547/22618986/7414d5d6-eb10-11e6-84ac-df30bd0961b2.png)

**Comment by kkateq** [comment]
@mohtamohit yes, completely unrelated to this repository, but you should submit your bug following this guide https://support.unity3d.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-

**Comment by mohtamohit** [comment]
@kkateq Thank you for the reference. :)
