### ISSUE TITLE
How to get started with this?

### ISSUE THREAD

**Issue by jknotten** [Unity-Technologies/Tanto#82]
Hi, I am very interested in a better code review tool for Unity files. At the moment we use rietveld, but would love to give Tanto a go to see where it is going. I tried about 6 months ago, but I could not work out how to get the login system working. Do you have hints, tips or instructions on how to get going with Tanto? Thanks John

**Comment by kkateq** [comment]
Hi, this tool heavily integrated with Mercurial source code management system used by Unity internally and it's not open sourced. So until that happens, I can't advise on how you could run this. Therefore we don't have any specific instructions yet.

**Comment by jknotten** [comment]
Ok, thanks for reply. I hope to try this product out as soon as it's available then.
